galaxy_info:
  author: dan@raydevs.com
  description: Fullstack Software developer

  license: license (GPL-2.0-or-later, MIT, etc)

  min_ansible_version: 2.9

  platforms:
   - name: Linux
   - name: OSX

  galaxy_tags:
    - zsh
