---
# defaults file for servutils/roles/zsh
user: "{{ ansible_env.USER }}"
shell_dst: "/usr/bin/zsh"
zshrc_path: "{{ ansible_env.HOME }}/.zshrc"
zshrc_lines:
  - 'PROMPT="%F{blue}${${(%):-%n}#zoltan-}%f ${PROMPT}"'
  - "alias ll='ls -alF'"
  - "alias la='ls -A'"
  - "alias l='ls -CF'"